name: Selenium tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'
  
jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Chrome        
        uses: browser-actions/setup-chrome@latest
          
      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Set up Selenium
        run: |
          echo "chrome: --headless --disable-gpu --no-sandbox" > ~/.config/chromium-flags.conf
          export CHROME_BIN=/usr/bin/chromium-browser
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Selenium tests
        run: python main.py
        
